#define HA_TRUE 1
#define HA_FALSE 0

#define HA_REQUIRED_VERSION_MAJOR 1
#define HA_REQUIRED_VERSION_MINOR 53
#define HA_REQUIRED_VERSION HA_REQUIRED_VERSION_MAJOR.HA_REQUIRED_VERSION_MINOR

#define HA_VERSION_MAJOR 1
#define HA_VERSION_MINOR 0
#define HA_VERSION HA_VERSION_MAJOR.HA_VERSION_MINOR
#define HA_BETA HA_FALSE

#define HA_MAX_SHADOWS_DISTANCE 2500.0
#define HA_MIN_SHADOWS_DISTANCE 60.0