class CfgPatches
{
	class THA_Sharks
	{
		units[]=
		{
			"GreatWhiteShark",
			"GreatWhiteShark2",
			"GreatWhiteShark3"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Data_F",
			"A3_Animals_F",
			"A3_Air_F"
		};
	};
};
class CfgMovesFish_Base_F
{
	access=1;
	collisionVertexPattern[]={};
	collisionGeomCompPattern[]={1};
	class Default
	{
		access=3;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=1;
		disableWeaponsLong=0;
		canreload=1;
		showWeaponAim=1;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=1;
		soundOverride="";
		soundEdge[]={0.5,1};
		soundEdge1=0.5;
		soundEdge2=1;
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]={};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1.75;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		leftHandIKCurve=0;
		rightHandIKCurve=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		showDisposableGun=0;
		headBobStrength=0.5;
		headBobMode=1;
	};
	class StandBase: Default
	{
		duty=-1;
		head="headDefault";
		speed=1e+010;
		relSpeedMin=0.7;
		relSpeedMax=1.1;
		looped=1;
		soundEnabled=1;
		enableDirectControl=0;
		disableWeapons=1;
		disableWeaponsLong=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
	};
	class ManActions
	{
		Stop="";
		StopRelaxed="";
		TurnL="";
		TurnR="";
		TurnLRelaxed="";
		TurnRRelaxed="";
		Default="";
		JumpOff="";
		ReloadMagazine="";
		ReloadMGun="";
		ReloadAT="";
		ReloadMortar="";
		ThrowGrenade="";
		WalkF="";
		WalkLF="";
		WalkRF="";
		WalkL="";
		WalkR="";
		WalkLB="";
		WalkRB="";
		WalkB="";
		SlowF="";
		SlowLF="";
		SlowRF="";
		SlowL="";
		SlowR="";
		SlowLB="";
		SlowRB="";
		SlowB="";
		FastF="";
		FastLF="";
		FastRF="";
		FastL="";
		FastR="";
		FastLB="";
		FastRB="";
		FastB="";
		EvasiveForward="";
		EvasiveLeft="";
		EvasiveRight="";
		EvasiveBack="";
		StartSwim="";
		StopSwim="";
		Down="";
		Up="";
		PlayerStand="";
		PlayerCrouch="";
		PlayerProne="";
		Lying="";
		Stand="";
		Combat="";
		Crouch="";
		CanNotMove="";
		Civil="";
		CivilLying="";
		FireNotPossible="";
		Die="";
		WeaponOn="";
		WeaponOff="";
		StrokeFist="";
		StrokeGun="";
		SitDown="";
		Salute="";
		BinocOn="";
		BinocOff="";
		PutDown="";
		PutDownEnd="";
		Medic="";
		Treated="";
		LadderOnDown="";
		LadderOnUp="";
		LadderOff="";
		LadderOffTop="";
		LadderOffBottom="";
		GetInLow="";
		GetInMedium="";
		GetInHigh="";
		GetOutLow="";
		GetOutMedium="";
		GetOutHigh="";
		TakeFlag="";
		HandGunOn="";
		LookAround="";
		Eat="";
		StopEat="";
		Rest="";
		StopRest="";
	};
	class Actions
	{
		class NoActions: ManActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			stance="ManStanceUndefined";
			upDegree=0;
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims
	{
		aimingDefault[]=
		{
			"head",
			1
		};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]=
		{
			"Head",
			1
		};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};
};
class CfgMovesGreatWhite: CfgMovesFish_Base_F
{
	skeletonName="GreatWhiteSharkSkeleton";
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
	class Default: Default
	{
		actions="GreatWhiteActions";
		collisionShape="THA_Sharks\GreatWhiteShark_collision.p3d";
	};
	class DefaultDie: Default
	{
	};
	class StandBase: Default
	{
		file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
	};
	class States
	{
		class GreatWhite_Swim: StandBase
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
			looped=1;
			speed=-1.8;
			interpolateTo[]=
			{
				"GreatWhite_Die",
				1,
				"GreatWhite_Die2",
				1
			};
			connectTo[]=
			{
				"GreatWhite_Stop",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1,
				"GreatWhite_Byte",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			equivalentTo="GreatWhite_Swim";
			variantsAI[]=
			{
				"GreatWhite_Swim",
				0.1,
				"GreatWhite_S1",
				0.47,
				"GreatWhite_S2",
				0.1,
				"GreatWhite_S3",
				0.33000001
			};
			variantAfter[]={0.82999998,0.82999998,0.82999998};
		};
		class GreatWhite_S1: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_slow_swimcycle.rtm";
			connectTo[]=
			{
				"GreatWhite_Swim",
				0.1
			};
			speed=-1.8;
			variantAfter[]={0.82999998,0.82999998,0.82999998};
		};
		class GreatWhite_S2: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
			connectTo[]=
			{
				"GreatWhite_Swim",
				0.1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			speed=-1.3;
			variantAfter[]={0.82999998,0.82999998,0.82999998};
		};
		class GreatWhite_S3: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_fast_swimcycle.rtm";
			connectTo[]=
			{
				"GreatWhite_Swim",
				0.1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			speed=-1.1;
			variantAfter[]={0.82999998,0.82999998,0.82999998};
		};
		class GreatWhite_Stop: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			connectTo[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_Byte: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_FrontByte.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			connectTo[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_ByteLeft: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_LeftByte.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			connectTo[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_ByteRight: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_RightByte.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1
			};
			connectTo[]=
			{
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_TurnLeft: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Left_swimcycle.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1
			};
			connectTo[]=
			{
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_TurnRight: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Right_swimcycle.rtm";
			looped=1;
			speed=-1.5;
			connectFrom[]=
			{
				
				{
					"GreatWhite_TurnRight",
					1,
					"GreatWhite_Swim",
					1,
					"GreatWhite_S1",
					1,
					"GreatWhite_S2",
					1,
					"GreatWhite_S3",
					1
				},
				"connectTo[] = {""GreatWhite_TurnRight""",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_TurnLeftFast: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Left_swimcycle.rtm";
			looped=1;
			speed=-0.80000001;
			connectFrom[]=
			{
				"GreatWhite_TurnLeftFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1
			};
			connectTo[]=
			{
				"GreatWhite_TurnLeftFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_TurnLeft",
				1
			};
		};
		class GreatWhite_TurnRightFast: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Right_swimcycle.rtm";
			looped=1;
			speed=-0.80000001;
			connectFrom[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1
			};
			connectTo[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_Dive: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
			looped=1;
			speed=-0.80000001;
			connectFrom[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1,
				"GreatWhite_SwimUp",
				1
			};
			connectTo[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_SwimUp: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_swimcycle.rtm";
			looped=1;
			speed=-0.80000001;
			connectFrom[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_S1",
				1,
				"GreatWhite_S2",
				1,
				"GreatWhite_S3",
				1,
				"GreatWhite_Dive",
				1
			};
			connectTo[]=
			{
				"GreatWhite_TurnRightFast",
				1,
				"GreatWhite_Swim",
				1,
				"GreatWhite_TurnRight",
				1,
				"GreatWhite_TurnLeft",
				1,
				"GreatWhite_TurnLeftFast",
				1
			};
		};
		class GreatWhite_Die: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Dead1.rtm";
			speed=-3.7;
			actions="NoActions";
			looped="False";
			variantsPlayer[]=
			{
				"Sharks_Die",
				0.5,
				"Sharks_Die2",
				0.5
			};
			variantsAI[]={};
			variantAfter[]={0,0,0};
			interpolateFrom[]=
			{
				"GreatWhite_Swim",
				0.02,
				"Sharks_Stop",
				0.2
			};
			interpolateTo[]=
			{
				"Sharks_Die2",
				1
			};
			terminal=1;
		};
		class GreatWhite_Die2: GreatWhite_Swim
		{
			file="THA_Sharks\Data\Anims\GreatWhiteShark_Dead1.rtm";
			speed=-2;
			looped=0;
			variantAfter[]={0,0,0};
		};
	};
	class Actions: Actions
	{
		class NoActions: NoActions
		{
			Stop="GreatWhite_Stop";
			StopRelaxed="GreatWhite_Stop";
			TurnL="GreatWhite_TurnLefFast";
			TurnR="GreatWhite_TurnRightFast";
			TurnLRelaxed="GreatWhite_TurnLef";
			TurnRRelaxed="GreatWhite_TurnRight";
			Default="GreatWhite_Swim";
			JumpOff="GreatWhite_Swim";
			StartSwim="GreatWhite_Swim";
			StopSwim="GreatWhite_Swim";
			WalkF="GreatWhite_Swim";
			SlowF="GreatWhite_Swim";
			FastF="GreatWhite_S2";
			EvasiveForward="GreatWhite_Swim";
			Down="GreatWhite_Swim_";
			Up="GreatWhite_Swim";
			PlayerStand="GreatWhite_Swim";
			PlayerCrouch="GreatWhite_Swim";
			PlayerProne="GreatWhite_Swim";
			Lying="GreatWhite_Swim";
			Stand="GreatWhite_Swim";
			Combat="GreatWhite_S2";
			Crouch="GreatWhite_Swim";
			CanNotMove="Sharks_Stop";
			Civil="GreatWhite_Swim";
			CivilLying="GreatWhite_Swim";
			FireNotPossible="GreatWhite_Swim";
			Die="GreatWhite_Die";
			Eat="GreatWhite_Byte";
			Rest="GreatWhite_Swim";
		};
		class GreatWhiteActions: NoActions
		{
			Stop="GreatWhite_Stop";
			StopRelaxed="GreatWhite_Stop";
			TurnL="GreatWhite_TurnLefFast";
			TurnR="GreatWhite_TurnRightFast";
			TurnLRelaxed="GreatWhite_TurnLef";
			TurnRRelaxed="GreatWhite_TurnRight";
			Default="GreatWhite_Swim";
			JumpOff="GreatWhite_Swim";
			StartSwim="GreatWhite_Swim";
			StopSwim="GreatWhite_Swim";
			WalkF="GreatWhite_Swim";
			SlowF="GreatWhite_Swim";
			FastF="GreatWhite_Swim";
			EvasiveForward="GreatWhite_Swim";
			Down="GreatWhite_Dive";
			Up="GreatWhite_SwimUp";
			PlayerStand="GreatWhite_Swim";
			PlayerCrouch="GreatWhite_Swim";
			PlayerProne="GreatWhite_Swim";
			Lying="GreatWhite_Swim";
			Stand="GreatWhite_Swim";
			Combat="GreatWhite_S2";
			Crouch="GreatWhite_Swim";
			CanNotMove="GreatWhite_Stop";
			Civil="GreatWhite_Swim";
			CivilLying="GreatWhite_Swim";
			FireNotPossible="GreatWhite_Swim";
			Die="GreatWhite_Die";
			Eat="GreatWhite_Byte";
			Rest="GreatWhite_Swim";
			turnSpeed=1;
			limitFast=2.5;
			useFastMove=1;
			upDegree="ManPosNoWeapon";
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]=
	{
		"GreatWhite_Swim",
		1,
		"GreatWhite_TurnLeft",
		1,
		"GreatWhite_TurnRight",
		1,
		"GreatWhite_TurnRightFast",
		1,
		"GreatWhite_TurnLeftFast",
		1,
		"GreatWhite_Byte",
		1
	};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]=
		{
			"THA_Pelvis",
			1
		};
		headDefault[]=
		{
			"THA_Pelvis",
			1
		};
	};
};
class CfgVehicleClasses
{
	class THA_SharksVehicleClass
	{
		displayName="THA_Sharks";
	};
};
class CfgVehicles
{
	class Animal_Base_F;
	class Fish_Base_F;
	class GreatWhiteShark: Fish_Base_F
	{
		scope=2;
		scopeCurator=2;
		model="THA_Sharks\GreatWhiteShark.p3d";
		displayName="GreatWhiteShark";
		moves="CfgMovesGreatWhite";
		icon="THA_Sharks\textures\icons\Shark_icon_ca.paa";
		editorPreview="THA_Sharks\textures\icons\GreatWhiteShark.paa";
		vehicleClass="THA_SharksVehicleClass";
		author="B@Co";
		hiddenSelections[]=
		{
			"camo"
		};
		wildAnimal=1;
		hasGeometry=1;
		humansDetectionRadius=100;
		runDistanceMax=3;
		maxTurnAngularVelocity=3;
		costTurnCoef=9.9999997e-006;
		minIdleTime=2;
		maxIdleTime=5;
		memoryPointAim="pilot";
		memoryPointCameraTarget="camera";
		minHeight="(-1 * waterDepth) + 0.1";
		avgHeight="((-1 * waterDepth)/4)";
		maxHeight=-0.1;
		canBleed=1;
		straightDistance=3;
		turning=0.5;
		armor=5;
		class VariablesScalar
		{
			_threatMaxRadius=0.1;
			_runDistanceMax=20;
			_movePrefer=1;
			_formationPrefer=0.1;
			_scareLimit=0.2;
			_dangerLimit=0.5;
			_walkSpeed=-1;
		};
		class VariablesString
		{
			_expSafe="waterDepth interpolate [2,3,0,1]";
			_expDanger="waterDepth interpolate [2,3,0,1]";
		};
		class EventHandlers
		{
			init="_this execVM ""\Tha_Sharks\scripts\shark_init.sqf""";
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"Tha_sharks\Textures\GreatWhiteShark.rvmat",
				//"Tha_sharks\Textures\GreatWhiteShark_wound1.rvmat",
				//"Tha_sharks\Textures\GreatWhiteShark_wound2.rvmat"
			};
		};
	};
	class GreatWhiteShark2: GreatWhiteShark
	{
		scope=2;
		scopeCurator=2;
		model="THA_Sharks\GreatWhiteShark2.p3d";
		displayName="GreatWhiteShark_scars";
		moves="CfgMovesGreatWhite";
		icon="THA_Sharks\textures\icons\Shark_icon_ca.paa";
		editorPreview="THA_Sharks\textures\icons\GreatWhiteShark.paa";
		vehicleClass="THA_SharksVehicleClass";
		author="B@Co";
	};
	class GreatWhiteShark3: Fish_Base_F
	{
		scope=2;
		scopeCurator=2;
		model="THA_Sharks\GreatWhiteShark.p3d";
		displayName="GreatWhiteShark_manhunter";
		moves="CfgMovesGreatWhite";
		icon="THA_Sharks\textures\icons\Shark_icon_ca.paa";
		editorPreview="THA_Sharks\textures\icons\GreatWhiteShark.paa";
		vehicleClass="THA_SharksVehicleClass";
		author="B@Co";
		hiddenSelections[]=
		{
			"camo"
		};
		wildAnimal=1;
		hasGeometry=1;
		humansDetectionRadius=100;
		runDistanceMax=3;
		maxTurnAngularVelocity=3;
		costTurnCoef=9.9999997e-006;
		minIdleTime=2;
		maxIdleTime=5;
		memoryPointAim="pilot";
		memoryPointCameraTarget="camera";
		minHeight="(-1 * waterDepth) + 0.1";
		avgHeight="((-1 * waterDepth)/4)";
		maxHeight=500;
		canBleed=1;
		straightDistance=3;
		turning=0.5;
		armor=5;
		class VariablesScalar
		{
			_threatMaxRadius=0.1;
			_runDistanceMax=20;
			_movePrefer=1;
			_formationPrefer=0.1;
			_scareLimit=0.2;
			_dangerLimit=0.5;
			_walkSpeed=-1;
		};
		class VariablesString
		{
			_expSafe="waterDepth interpolate [2,3,0,1]";
			_expDanger="waterDepth interpolate [2,3,0,1]";
		};
		class EventHandlers
		{
			init="_this execVM ""\Tha_Sharks\scripts\shark_init.sqf""";
		};
	};
};
class CfgSounds
{
	class short_heavy_splash
	{
		name="short_heavy_splash";
		sound[]=
		{
			"\Tha_Sharks\sounds\short_heavy_splash.ogg",
			0.70794576,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
	class large_splat
	{
		name="large_splat";
		sound[]=
		{
			"\Tha_Sharks\sounds\large_splat.ogg",
			0.79432821,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
	class Scared_diver
	{
		name="Scared_diver";
		sound[]=
		{
			"\Tha_Sharks\sounds\scary_diver3db.ogg",
			0.89125091,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
	class bonecrunch
	{
		name="Scared_diver";
		sound[]=
		{
			"\Tha_Sharks\sounds\bonecrunch.ogg",
			0.89125091,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
	class sharkbait2
	{
		name="Scared_diver";
		sound[]=
		{
			"\Tha_Sharks\sounds\sharkbait2.ogg",
			0.89125091,
			1
		};
		titles[]=
		{
			0,
			""
		};
	};
};
class ComplexEffect
{
	class underwaterBleeding
	{
		simulation="particles";
		type="underwaterBleeding";
		position[]={0,0,0};
		lifeTime=12.5;
		qualityLevel=-1;
		start=1;
		enabled=1;
		smokeGenMinDist=100;
		smokeGenMaxDist=500;
		smokeSizeCoef=2;
		smokeIntervalCoef=4;
	};
};
class CfgCloudlets
{
	class underwaterBleeding
	{
		position[]={0,0,0};
		positionVar[]={0,0,0};
		positionVarConst[]={0,0,0};
		interval=0.02;
		circleRadius=0;
		circleVelocity[]={0,0,0};
		particleShape="\A3\data_f\ParticleEffects\Universal\smoke.p3d";
		particleFSNtieth=1;
		particleFSIndex=0;
		particleFSFrameCount=1;
		particleFSLoop=0;
		angle=0;
		angleVar=360;
		animationName="";
		particleType="Billboard";
		timerPeriod=1;
		lifeTime=20;
		lifeTimeVar=0;
		moveVelocity[]={0,0,0.1};
		MoveVelocityVar[]={0,0,0};
		MoveVelocityVarConst[]={0,0,0};
		rotationVelocity=0;
		rotationVelocityVar=0;
		weight=1.275;
		volume=1;
		rubbing=5;
		size[]={0.1,0.80000001,0.89999998};
		sizeCoef=1;
		sizeVar=0.5;
		color[]=
		{
			{0.40000001,0,0,1},
			{0.1,0,0,1},
			{0,0,0,0.5},
			{0.050000001,0,0,0.050000001},
			{0.050000001,0,0,0.0099999998}
		};
		colorCoef[]={0.1,0,0,1};
		colorVar[]={0,0,0,0};
		animationSpeed[]={1};
		animationSpeedCoef=1;
		randomDirectionPeriod=1;
		randomDirectionIntensity=0.029999999;
		onTimerScript="";
		beforeDestroyScript="";
		blockAIVisibility=0;
		randomDirectionPeriodVar=0;
		randomDirectionIntensityVar=0;
		destroyOnWaterSurface=-1;
	};
};
class cfgFunctions
{
	class SHARK
	{
		class movement
		{
			class depthToTarget
			{
				file="\Tha_Sharks\functions\fnc_depthToTarget.sqf";
				description="Proper shark depth changes according to target's depth. Scheduled environment.";
			};
			class huntingBehavior
			{
				file="\Tha_Sharks\functions\fnc_huntingBehavior.sqf";
				description="Shark behaviour.";
			};
		};
		class damage
		{
			class underwaterBleeding
			{
				file="\Tha_Sharks\functions\fnc_underwaterBleeding.sqf";
				description="underwater bleeding effect.";
			};
		};
	};
};
class cfgMods
{
	author="B@Co, Malcain";
	timepacked="1551543393";
};
