// Generated by unRap v1.06 by Kegetys

class CfgIdentities {
	class BP_Zombie1 {
		name = "BP_Zombie1";
		face = "BP_Zombie1";
		glasses = "None";
		speaker = "NoVoice";
		pitch = 1;
	};
	class BP_Zombie2 {
		name = "BP_Zombie2";
		face = "BP_Zombie2";
		glasses = "None";
		speaker = "NoVoice";
		pitch = 1;
	};
	class BP_Zombie3 {
		name = "BP_Zombie3";
		face = "BP_Zombie3";
		glasses = "None";
		speaker = "NoVoice";
		pitch = 1;
	};
	class BP_Zombie4 {
		name = "BP_Zombie4";
		face = "BP_Zombie4";
		glasses = "None";
		speaker = "NoVoice";
		pitch = 1;
	};
	class BP_Zombie5 {
		name = "BP_Zombie5";
		face = "BP_Zombie5";
		glasses = "None";
		speaker = "NoVoice";
		pitch = 1;
	};
};
