/*
	Breaking Point Mod for Arma 3

	Released under Arma Public Share Like Licence (APL-SA)
	https://www.bistudio.com/community/licenses/arma-public-license-share-alike

	Alderon Games Pty Ltd
*/

//class CfgMovesDog_F;
class CfgMovesDog_BP : CfgMovesAnimal_Base_F 
{
	access = 0;
	enableDirectControl=0;
	skeletonName="Dog_F";
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a"
	};
	collisionGeomCompPattern[]={1};
	class Default: Default
	{
		access=1;
		file="";
		looped=1;
		speed=0.5;
		disableWeapons=1;
		enableOptics=1;
		disableWeaponsLong=0;
		canreload=1;
		showWeaponAim=1;
		enableMissile=0;
		enableBinocular=0;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		onLandBeg=0;
		onLandEnd=0;
		onLadder=0;
		canPullTrigger=1;
		duty=-0.50999999;
		predictSpeedCoef=1;
		visibleSize=1;
		aimPrecision=1;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=1;
		soundOverride="";
		soundEdge[]={0.5,1};
		soundEdge1=0.5;
		soundEdge2=1;
		terminal=0;
		limitGunMovement=1;
		variantsPlayer[]={};
		variantsAI[]={};
		equivalentTo="";
		connectAs="";
		variantAfter[]={5,10,20};
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		aiming="aimingNo";
		leaning="aimingNo";
		untiltWeapon="aimingNo";
		aimingBody="aimingUpDefault";
		legs="legsNo";
		head="headDefault";
		leaningFactorBeg=0;
		leaningFactorEnd=0;
		leaningFactorZeroPoint=-1;
		leaningCorrectionAngleBeg=0;
		leaningCorrectionAngleEnd=0;
		interpolationSpeed=6;
		interpolationRestart=0;
		hasCollShapeSafe=0;
		collisionShapeSafe="";
		boundingSphere=1;
		enableDirectControl=1;
		enableAutoActions=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		leftHandIKCurve=0;
		rightHandIKCurve=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		weaponIK=0;
		preload=0;
		walkcycles=1;
		forceAim=0;
		//ragdoll = 1;
		showDisposableGun=0;
		headBobStrength=0.5;
		headBobMode=1;
		collisionShape="A3\animals_f_beta\dog\Dog_CollShape.p3d";
	};
	class StandBase: Default
	{
		aiming="aimingDefault";
		disableWeapons=1;
		leaningFactorBeg=1;
		leaningFactorEnd=1;
	};
	class DefaultDie: Default
	{
		aiming="aimingNo";
		legs="legsNo";
		head="headNo";
		disableWeapons=1;
		interpolationRestart=1;
		soundOverride="fallbody";
		soundEdge1=0.44999999;
		soundEdge2=0.44999999;
	};
	class States
	{
		class Dog_Idle_Stop: StandBase
		{
			enableDirectControl=1;
			actions="FinActions";
			duty=-1;
			file="\A3\animals_f_beta\Dog\data\Anim\dogStop";
			showWeaponAim=0;
			disableWeapons=1;
			disableWeaponsLong=1;
			variantsAI[]=
			{
				"Dog_Idle_01",
				0.039999999,
				"Dog_Idle_02",
				0.039999999,
				"Dog_Idle_03",
				0.039999999,
				"Dog_Idle_04",
				0.039999999,
				"Dog_Idle_05",
				0.039999999,
				"Dog_Idle_06",
				0.039999999,
				"Dog_Idle_07",
				0.039999999,
				"Dog_Idle_08",
				0.039999999,
				"Dog_Idle_09",
				0.039999999,
				"Dog_Idle_10",
				0.039999999,
				"Dog_Idle_Sit01",
				0.039999999,
				"Dog_Idle_Sit02",
				0.039999999,
				"Dog_Idle_Sit03",
				0.039999999,
				"Dog_Idle_Sit04",
				0.039999999,
				"Dog_Idle_Sit05",
				0.039999999,
				"Dog_Idle_Sit06",
				0.039999999,
				"Dog_Idle_Sit07",
				0.039999999,
				"Dog_Idle_Sit08",
				0.039999999,
				"Dog_Idle_Bark",
				0.039999999,
				"Dog_Idle_Growl",
				0.039999999,
				"Dog_Idle_Walk",
				0.1,
				"Dog_Idle_Run",
				0.050000001,
				"Dog_Idle_Sprint",
				0.050000001
			};
			variantsPlayer[]={};
			variantAfter[]={3,6,9};
			speed=1e+010;
			relSpeedMin=0.69999999;
			relSpeedMax=1.1;
			looped=1;
			soundEnabled=0;
			connectTo[]=
			{
				"Dog_TurnL",
				0.1,
				"Dog_TurnR",
				0.1
			};
			interpolateTo[]=
			{
				"Dog_Idle_Stop",
				0.050000001,
				"Dog_Idle_01",
				0.050000001,
				"Dog_Idle_02",
				0.050000001,
				"Dog_Idle_03",
				0.050000001,
				"Dog_Idle_04",
				0.050000001,
				"Dog_Idle_05",
				0.050000001,
				"Dog_Idle_06",
				0.050000001,
				"Dog_Idle_07",
				0.050000001,
				"Dog_Idle_08",
				0.050000001,
				"Dog_Idle_09",
				0.050000001,
				"Dog_Idle_10",
				0.050000001,
				"Dog_Idle_Sit01",
				0.050000001,
				"Dog_Idle_Sit02",
				0.050000001,
				"Dog_Idle_Sit03",
				0.050000001,
				"Dog_Idle_Sit04",
				0.050000001,
				"Dog_Idle_Sit05",
				0.050000001,
				"Dog_Idle_Sit06",
				0.050000001,
				"Dog_Idle_Sit07",
				0.050000001,
				"Dog_Idle_Sit08",
				0.050000001,
				"Dog_Idle_Bark",
				0.050000001,
				"Dog_Idle_Growl",
				0.050000001,
				"Dog_Idle_Walk",
				0.2,
				"Dog_Idle_Run",
				0.02,
				"Dog_Idle_Sprint",
				0.02,
				"Dog_Die",
				0.2,
				"Dog_Walk",
				0.5,
				"Dog_Run",
				0.5,
				"Dog_Sprint",
				0.5,
				"Dog_Sit",
				0.5,
				"Dog_Stop",
				0.5,
				"Dog_TurnL",
				0.1,
				"Dog_TurnR",
				0.1
			};
			enableBinocular=1;
			leftHandIKBeg=1;
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			interpolationSpeed=1;
			preload=1;
		};
		class Dog_TurnL: Dog_Idle_Stop
		{
			file="\A3\animals_f_beta\Dog\data\anim\dogTurnL";
			connectTo[]=
			{
				"Dog_Idle_Stop",
				0.1,
				"Dog_Stop",
				0.1
			};
			interpolateTo[]=
			{
				"Dog_Idle_Stop",
				0.1,
				"Dog_Stop",
				0.1
			};
			speed=1;
		};
		class Dog_TurnR: Dog_TurnL
		{
			file="\A3\animals_f_beta\Dog\data\anim\dogTurnR";
		};
		class Dog_Idling: Dog_Idle_Stop
		{
			variantAfter[]={3,6,9};
			equivalentTo="Dog_Idle_Stop";
			speed=-3;
		};
		class Dog_Idle_01: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle9";
		};
		class Dog_Idle_02: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle1";
		};
		class Dog_Idle_03: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle2";
		};
		class Dog_Idle_04: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle3";
		};
		class Dog_Idle_05: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle4";
		};
		class Dog_Idle_06: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle5";
		};
		class Dog_Idle_07: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle6";
		};
		class Dog_Idle_08: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle7";
		};
		class Dog_Idle_09: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle8";
			speed=-4;
		};
		class Dog_Idle_10: Dog_Idling
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogIdle9";
		};
		class Dog_Idle_Sitting: Dog_Idle_Stop
		{
			variantAfter[]={3,6,9};
			speed=-3;
			interpolationSpeed=0.5;
		};
		class Dog_Idle_Sit01: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle";
		};
		class Dog_Idle_Sit02: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle1";
		};
		class Dog_Idle_Sit03: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle3";
		};
		class Dog_Idle_Sit04: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle3";
		};
		class Dog_Idle_Sit05: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle4";
		};
		class Dog_Idle_Sit06: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle5";
		};
		class Dog_Idle_Sit07: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle6";
		};
		class Dog_Idle_Sit08: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle7";
		};
		class Dog_Idle_Bark: Dog_Idle_Stop
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogBarkingLoop";
			speed=-3;
			variantsAI[]={};
			variantAfter[]={3,6,9};
			interpolateTo[]=
			{
				"Dog_Idle_Stop",
				0.1,
				"Dog_Die",
				0.2
			};
			looped=1;
			soundOverride = "z_dog_bark_2";
			soundEnabled = 1;
			soundEdge[] = {0.25};
		};
		class Dog_Idle_Growl: Dog_Idle_Stop
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogGrowlingLoop";
			speed=-1.5; //-3
			variantsAI[]={};
			variantAfter[]={3,6,9};
			equivalentTo="Dog_Idle_Growl";
			interpolateTo[]=
			{
				"Dog_Idle_Stop",
				0.1,
				"Dog_Die",
				0.2
			};
			looped=1;
		};
		class Dog_Idle_Sprint: Dog_Idle_Stop
		{
			actions="FinSprint";
			file="\A3\animals_f_beta\Dog\data\Anim\dogRun";
			duty=0.5;
			speed=-0.75; //-1.47
			connectTo[]={};
			interpolateTo[]=
			{
				"Dog_Idle_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Idle_Sprint",
				0.02,
				"Dog_Idle_Walk",
				0.02,
				"Dog_Die_Sprint",
				0.02
			};
			variantsAI[]={};
		};
		class Dog_Idle_Run: Dog_Idle_Stop
		{
			file="\A3\animals_f_beta\Dog\data\Anim\dogTrot";
			duty=-0.5;
			speed=1.15; //-1.63;
			connectTo[]={};
			interpolateTo[]=
			{
				"Dog_Idle_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Idle_Sprint",
				0.02,
				"Dog_Idle_Walk",
				0.02,
				"Dog_Die_Run",
				0.02
			};
			variantsAI[]={};
		};
		class Dog_Idle_Walk: Dog_Idle_Stop
		{
			actions="FinRun";
			duty=-0.69999999;
			file="\A3\animals_f_beta\Dog\data\Anim\dogWalk";
			speed=-2.03;
			variantAfter[]={3,10,20};
			connectTo[]={};
			interpolateTo[]=
			{
				"Dog_Idle_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Idle_Sprint",
				0.02,
				"Dog_Idle_Walk",
				0.02,
				"Dog_Die",
				0.02
			};
			variantsAI[]={};
		};
		class Dog_Die: DefaultDie
		{
			enableDirectControl=0;
			actions="NoActions";
			file="\A3\animals_f_beta\Dog\data\Anim\dogDeath";
			speed=1.2;
			looped=0;
			variantsPlayer[]={};
			variantsAI[]={};
			variantAfter[]={0,0,0};
			terminal=1;
		};
		class Dog_Die_Sit: Dog_Die
		{
			file="\A3\animals_f_beta\Dog\data\Anim\dogSit2Death";
			terminal=1;
		};
		class Dog_Die_Sprint: Dog_Die
		{
			file="\A3\animals_f_beta\Dog\data\Anim\dogRunDeath";
			terminal=1;
		};
		class Dog_Die_Run: Dog_Die
		{
			file="\A3\animals_f_beta\Dog\data\Anim\dogTrotDeath";
			terminal=1;
		};
		class Dog_Stop: Dog_Idle_Stop
		{
			actions="FinForceStop";
			connectTo[]=
			{
				"Dog_TurnL",
				0.1,
				"Dog_TurnR",
				0.1
			};
			interpolateTo[]=
			{
				"Dog_Idle_01",
				0.050000001,
				"Dog_Idle_02",
				0.050000001,
				"Dog_Idle_03",
				0.050000001,
				"Dog_Idle_04",
				0.050000001,
				"Dog_Idle_05",
				0.050000001,
				"Dog_Idle_06",
				0.050000001,
				"Dog_Idle_07",
				0.050000001,
				"Dog_Idle_08",
				0.050000001,
				"Dog_Idle_09",
				0.050000001,
				"Dog_Idle_10",
				0.050000001,
				"Dog_Idle_Stop",
				0.050000001,
				"Dog_Die",
				0.2,
				"Dog_Walk",
				0.5,
				"Dog_Run",
				0.5,
				"Dog_Sprint",
				0.5,
				"Dog_Sit",
				0.5,
				"Dog_TurnL",
				0.1,
				"Dog_TurnR",
				0.1
			};
			variantsAI[]=
			{
				"Dog_Idle_01",
				0.039999999,
				"Dog_Idle_02",
				0.039999999,
				"Dog_Idle_03",
				0.039999999,
				"Dog_Idle_04",
				0.039999999,
				"Dog_Idle_05",
				0.039999999,
				"Dog_Idle_06",
				0.039999999,
				"Dog_Idle_07",
				0.039999999,
				"Dog_Idle_08",
				0.039999999,
				"Dog_Idle_09",
				0.039999999,
				"Dog_Idle_10",
				0.039999999
			};
		};
		class Dog_Sit: Dog_Idle_Sitting
		{
			file="\A3\animals_f_beta\Dog\Data\anim\dogSit2Idle";
			actions="FinForceSit";
			variantsAI[]={};
			interpolateTo[]=
			{
				"Dog_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Sprint",
				0.02,
				"Dog_Walk",
				0.02,
				"Dog_Die_Sit",
				0.02,
				"Dog_Sit",
				0.02,
				"Dog_Stop",
				0.02
			};
		};
		class Dog_Walk: Dog_Idle_Walk
		{
			actions="FinForceWalk";
			interpolateTo[]=
			{
				"Dog_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Sprint",
				0.02,
				"Dog_Walk",
				0.02,
				"Dog_Die",
				0.02,
				"Dog_Sit",
				0.02,
				"Dog_Stop",
				0.02
			};
		};
		class Dog_Run: Dog_Idle_Run
		{
			actions="FinForceRun";
			interpolateTo[]=
			{
				"Dog_Run",
				0.02,
				"Dog_Idle_Stop",
				0.02,
				"Dog_Sprint",
				0.02,
				"Dog_Walk",
				0.02,
				"Dog_Stop",
				0.02,
				"Dog_Die_Run",
				0.02
			};
		};
		class Dog_Sprint: Dog_Idle_Sprint
		{
			actions="FinForceSprint";
			interpolateTo[]=
			{
				"Dog_Run",
				0.02,
				"Dog_Sprint",
				0.02,
				"Dog_Stop",
				0.02,
				"Dog_Die_Sprint",
				0.02
			};
		};
	};
	class Actions: Actions
	{
		class NoActions: NoActions
		{
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree=0;
		};
		class FinActions: NoActions
		{
			Stop="Dog_Idle_Stop";
			StopRelaxed="Dog_Idle_Stop";
			TurnL="Dog_TurnL";
			TurnR="Dog_TurnR";
			TurnLRelaxed="Dog_TurnL";
			TurnRRelaxed="Dog_TurnR";
			Default="Dog_Idling";
			JumpOff="Dog_Idle_Stop";
			WalkF="Dog_Idle_Walk";
			SlowF="Dog_Idle_Run";
			FastF="Dog_Idle_Sprint";
			EvasiveForward="Dog_Idle_Sprint";
			Down="Dog_Idle_Stop";
			Up="Dog_Idle_Stop";
			PlayerStand="Dog_Idle_Stop";
			PlayerProne="Dog_Idle_Stop";
			PlayerCrouch="Dog_Idle_Sitting";
			Crouch="Dog_Idle_Sitting";
			Lying="Dog_Idle_Stop";
			Stand="Dog_Idle_Stop";
			Combat="Dog_Idle_Stop";
			CanNotMove="Dog_Idle_Stop";
			Civil="Dog_Idle_Stop";
			CivilLying="Dog_Idle_Stop";
			FireNotPossible="Dog_Idle_Stop";
			Die="Dog_Die";
			turnSpeed=8;
			limitFast=5.5;
			useFastMove=0;
			upDegree="ManPosNoWeapon";
		};
		class FinRun: FinActions
		{
			Die="Dog_Die_Run";
		};
		class FinSprint: FinActions
		{
			FastF="Dog_Idle_Sprint";
			EvasiveForward="Dog_Idle_Sprint";
			Die="Dog_Die_Sprint";
			turnSpeed=2;
			limitFast=5.5;
			useFastMove=1;
		};
		class FinSit: FinActions
		{
			Stop="Dog_Idle_Sitting";
			StopRelaxed="Dog_Idle_Sitting";
			Die="Dog_Die_Sit";
		};
		class FinForceStop: FinActions
		{
			CivilLying="Dog_Stop";
		};
		class FinForceSit: FinSit
		{
			CivilLying="Dog_Sit";
		};
		class FinForceWalk: FinActions
		{
			CivilLying="Dog_Walk";
		};
		class FinForceRun: FinRun
		{
			CivilLying="Dog_Run";
		};
		class FinForceSprint: FinSprint
		{
			CivilLying="Dog_Sprint";
		};
	};
	class Interpolations
	{
	};
	transitionsInterpolated[]={};
	transitionsSimple[]={};
	transitionsDisabled[]={};
	class BlendAnims: BlendAnims
	{
		aimingDefault[]=
		{
			"head",
			1,
			"head",
			1,
			"head",
			1
		};
		untiltWeaponDefault[]={};
		legsDefault[]={};
		headDefault[]={};
		aimingNo[]={};
		legsNo[]={};
		headNo[]={};
		aimingUpDefault[]={};
	};	
};